var num1 = 4.0;
console.log(("The first number"), num1);
var num2 = -13.9;
console.log(("The second number"), num2);
var num3 = Infinity * Infinity;
console.log(("The third number"), num3);
var num4 = 96 / 2 * 85;
console.log(("The fourth number"), num4);
var str1 = "I'm great";
console.log(("The first string"), str1);
var str2 = "dank memes";
console.log(("The second string"), str2);
var str3 = 'holy 1337 sh*t';
console.log(("The third string"), str3);
var boolean1 = undefined === (Infinity / Infinity);
console.log(("The first boolean"), boolean1);
var boolean2 = typeof [] === 'object'; 
console.log(("The second boolean"), boolean2);
var und = dofjeldfj;
console.log(("Undefined-ness"), und);